# Generated by Django 3.2 on 2022-07-31 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户详情表', 'verbose_name_plural': '用户详情表'},
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='b_userinfo',
        ),
    ]
