# Generated by Django 3.2 on 2022-07-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='tag_articles', to='blog.TagOfArticle', verbose_name='文章标题'),
        ),
    ]
