# Generated by Django 3.2 on 2022-07-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagofarticle',
            options={},
        ),
    ]
