# Generated by Django 3.2 on 2022-07-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_tagofarticle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='tag_articles', to='blog.TagOfArticle', verbose_name='文章标题'),
        ),
    ]
