# Generated by Django 3.2 on 2022-07-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.IntegerField(default=1, verbose_name='作者名称'),
            preserve_default=False,
        ),
    ]
